"""Update table

Revision ID: a866e47f5273
Revises: b491e2d146b4
Create Date: 2023-10-01 17:02:46.453675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a866e47f5273'
down_revision: Union[str, None] = 'b491e2d146b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('games', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('games', 'is_active')
    # ### end Alembic commands ###
