"""Update table

Revision ID: ba2da0a775e4
Revises: a866e47f5273
Create Date: 2023-10-01 18:04:55.925046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2da0a775e4'
down_revision: Union[str, None] = 'a866e47f5273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(), nullable=True))
    op.add_column('games', sa.Column('current_player', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('players_queue', sa.ARRAY(sa.BigInteger()), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['current_player'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'players_queue')
    op.drop_column('games', 'current_player')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
